name: Engine-Deployment

on:
  workflow_dispatch: 
  push: 
    branches: 
      - main
    paths: 
      - 'apps/engine/**'
      - 'packages/common/**'
      - 'packages/db/**'
      - '.github/workflows/deploy-engine.yml'
      - 'docker/Dockerfile.engine'

jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.engine
          push: true
          tags: |
            ikrambagban/exness-engine:${{ github.sha }}
            ikrambagban/exness-engine:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            docker pull ikrambagban/exness-engine:${{ github.sha }}
            docker network inspect exness-network || docker network create exness-network
            docker stop exness-engine || true
            docker rm exness-engine || true
            docker run -d \
              --name exness-engine \
              --restart always \
              --network exness-network \
              -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              -e REDIS_URL="${{ secrets.REDIS_URL }}" \
              -e NODE_ENV="production" \
              ikrambagban/exness-engine:${{ github.sha }}
